let nombre=prompt("Dime tu nombre")
let apellido=prompt("Dime tu apellido")
let n1=parseInt(prompt("DIme el primer numero"))
let n2=parseInt(prompt("DIme el segundo numero"))
let n3=parseInt(prompt("DIme el tercero numero"))
console.log(`${nombre} ${apellido}`)
console.log(n1+n2+n3)
console.log(n1*n2*n3)
console.log(n1/n3)